spring.application.name=portal-solicitacoes

spring.datasource.url=jdbc:postgresql://localhost:5433/portal_solicitacoes
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG
server.port=8080

springdoc.swagger-ui.csrf.enabled=true
springdoc.swagger-ui.csrf.cookie-name=XSRF-TOKEN
springdoc.swagger-ui.csrf.header-name=X-XSRF-TOKEN